### ISSUE TITLE
Travis CI build keeps failing

### ISSUE THREAD

**Issue by jphellemons** [jphellemons/CommandAsSql#6]
The .travis.yml file is broken. It needs to build, (run tests) and if succeeded, pack and push to nuget.
It has several issues.
one of them: Cannot open assembly 'nuget.exe': No such file or directory.
And I have tried several things as you can see in the commits. So I could use some help here.

**Comment by jphellemons** [comment]
Moved to AppVeyor CI

**Comment by birbilis** [comment]
Have you seen this thread? 
https://stackoverflow.com/questions/41509608/how-do-i-deploy-nuget-packages-in-travis-ci
might have some useful info

**Comment by jphellemons** [comment]
Lol, I even referenced it from my travis yaml file haha but could not get it to work for .Net Standard lib and an .Net core xunit project. AppVeyor works now, so it's all good 👍
